import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-8 flex flex-col h-screen bg-[#D6DEE7]">
          <div className="flex-grow w-full rounded-3xl bg-white text-black py-32 px-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
